config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :shops, except: %i[destroy]
  resources :cloths
  resources :shelves, :colors, :types, except: :show

  get '/managments', to: 'managments#shop', as: 'managments'
  get '/managments/main', to: 'managments#main', as: 'managment_main'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cloth.rb
class Cloth < ApplicationRecord
  belongs_to :shelf
  belongs_to :color
  belongs_to :type
  belongs_to :user
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :cloths
end

app/models/shelf.rb
class Shelf < ApplicationRecord
  belongs_to :shop
  has_many :cloths
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :shelves
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :cloths
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:customer, :owner]
  belongs_to :shop, optional: true
  has_many :cloths
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    "#{last_name}, #{first_name}"
  end
end

app/controllers/cloths_controller.rb
class ClothsController < ApplicationController
  before_action :set_cloth, except: %i[index new create]

  def index
    if current_user.owner?
      @cloths = policy_scope(Cloth.where("shelf_id = ?", current_user.shop.shelf_ids))
      # raise
    else
      @cloths = policy_scope(Cloth.where("user_id = ?", current_user.id))
    end
  end

  def show
    authorize(@cloth)
  end

  def new
    @cloth = Cloth.new
    authorize(@cloth)
  end

  def create
    @cloth = Cloth.new(cloth_params)
    authorize(@cloth)
    @cloth.user = current_user
    @cloth.save!
    redirect_to cloth_path(@cloth)
  end

  def edit
  end

  def update
    @cloth.update(cloth_params)
  end

  def destroy
    @cloth.destroy
  end

  private

  def set_cloth
    @cloth = Cloth.find(params[:id])
  end

  def cloth_params
    params.require(:cloth).permit(:type_id, :color_id, :shelf_id, :category,
    :wash_type, :delivery, :completed, :pick_up_date, :price)
  end
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController

  def new
    @color = Color.new
    authorize(@color)
  end

  def create
    @color = Color.new(color_params)
    authorize(@color)
    if @color.save!
      redirect_to managment_main_path
    else
      render "colors/new"
    end
  end

  def update
    @color = Color.find(params[:id])
    authorize(@color)
    @color.update(color_params)
    redirect_to managment_main_path
  end

  private

  def color_params
    params.require(:color).permit(:name)
  end
end

app/controllers/managments_controller.rb
class ManagmentsController < ApplicationController

  def main
    authorize :managment, :main?
    # @shop = Shop.find_by user_id: current_user.id
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  
  def home
  end
end

app/controllers/shelves_controller.rb
class ShelvesController < ApplicationController

  def index
    @shelves = policy_scope(Shelf.where(shop_id: current_user.shop_id))
  end
  
  def new
    @shelf = Shelf.new
    authorize(@shelf)
  end

  def create
    @shelf = Shelf.new(shelf_params)
    authorize(@shelf)
    @shelf.shop = Shop.find_by user_id: current_user.id
    if @shelf.save!
      redirect_to managment_main_path
    else
      render "shelves/new"
    end
  end

  def update
    @shelf = Shelf.find(params[:id])
    authorize(@shelf)
    @shelf.update(shelf_params)
    redirect_to managment_main_path
  end

  private

  def shelf_params
    params.require(:shelf).permit(:name)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[show edit update]

  def index
    @shops = policy_scope(Shop.where(user_id: current_user.id))
  end

  def show
    authorize(@shop)
  end

  def new
    @shop = Shop.new
    authorize(@shop)
  end

  def create
    @shop = Shop.new(shop_params)
    authorize(@shop)
    @shop.user = current_user

    if @shop.save
      redirect_to shop_path(@shop)
      current_user.shop = @shop
      current_user.save
    else
      render 'shops/new'
    end
  end

  def edit
    authorize(@shop)
  end

  def update
    authorize(@shop)
    if @shop.update(shop_params)
      redirect_to shop_path(@shop)
    else
      redirect_to shop_path(@shop)
    end
  end

  private

  def set_shop
    @shop = Shop.find_by user_id: current_user.id
  end

  def shop_params
    params.require(:shop).permit(:name, :address, :phone, :city)
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController

  def new
    @type = Type.new
    authorize(@type)
  end

  def create
    @type = Type.new(type_params)
    authorize(@type)
    if @type.save!
      redirect_to managment_main_path
    else
      render "types/new"
    end
  end

  def update
    @type = Type.find(params[:id])
    authorize(@type)
    @type.update(type_params)
    redirect_to managment_main_path
  end

  private

  def type_params
    params.require(:type).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/cloths_helper.rb
module ClothsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/managments_helper.rb
module ManagmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shelves_helper.rb
module ShelvesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/cloths/index.html.erb
<% unless @cloths.empty? %>
  <% @cloths.each do |cloth| %>
    <%= link_to(cloth) do %>
    <ul>
      <li> <h3><%= cloth.user.first_name %> <%= cloth.user.last_name %>  <%= cloth.type.name %></h3></li>
    </ul>
    <% end %>
  <% end %>
<% else %>
  <h2>Δεν υπάρχουν ρούχα αυτή τη στιγμή</h2>
<% end %>

app/views/cloths/new.html.erb
<%= simple_form_for @cloth do |f| %>
  <div class="d-flex flex-column">
    <%= f.label "Είδος" %>
    <%= f.input :type_id, collection: Type.all, label: false %>
    <%= f.label "Χρώμα" %>
    <%= f.input :color_id, collection: Color.all, label: false %>
    <%= f.label "Ράφι" %>
    <%= f.association :shelf, label: false %>
  </div>
  <div class="field">
    <%= f.select :user_id, User.where(shop_id: current_user.shop_id).pluck(:last_name) %>
  </div>

  <div class="d-flex justify-content-between">
    <%= f.input :category, collection: ["Ανδρικό", "Γυναικείο", "Παιδικό"], label: "Κατηγορία"%> <br><br>
    <%= f.input :wash_type, collection: ["Στεγνό καθάρισμα", "Υγρό καθάρισμα", "Σιδέρωμα"], label: "Τρόπος καθαρίσματος" %>
  </div>

  <div class="d-flex" %>
    <%= f.input :delivery, as: :boolean, checked_value: true, unchecked_value: false, :label_html => { :class => 'checkbox-inline' }, label: "Παράδοση" %>
    <%# <%= f.input :completed, as: :boolean, checked_value: true, unchecked_value: false, :label_html => { :class => 'checkbox-inline' }, label: "Έτοιμο" %>
  </div>

  <%= f.input :pick_up_date, as: :date, label: "Ημερομηνία παράδωσης"%>

  <%= f.label "Κόστος" %>
  <%= f.input_field :price %>


  <div class="d-flex mt-4">
    <%= f.button :submit, "Δημιουργία ρούχου", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cloths/show.html.erb
<h2><%= @cloth.type.name %></h2>

app/views/colors/new.html.erb
<%= simple_form_for @color do |f| %>
  <%= f.label "Νέο χρώμα" %>
  <%= f.input_field :name %>
  <%= f.button :submit, "Δημιουργία χρώματος", class: "btn btn-primary" %>
<% end %>

app/views/shops/edit.html.erb
<%= simple_form_for @shop do |f| %>
  <%= f.input :name, label: "Όνομα καταστήματος" %>
  <%= f.input :address, label: "Διεύθυση" %>
  <%= f.input :city, label: "Πόλη" %>
  <%= f.input :phone, label: "Τηλέφωνο" %>
  <%= f.button :submit, "Αποθήκευση", class: "btn btn-primary" %>
<% end %>

app/views/shops/index.html.erb
<% if @shops.empty? && current_user.owner? %>
  <%= link_to 'Δημιουργία νέου καταστήματος', new_shop_path, class: "btn btn-primary" %>
<% else %>
  <% @shops.each do |shop| %>
  <h1><%=link_to shop.name , shop_path(shop)%> </h1>
  <br>
  <%= link_to "Επεξεργασία", edit_shop_path(shop), class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/shops/new.html.erb
<%= simple_form_for @shop do |f| %>
  <%= f.input :name, label: "Όνομα καταστήματος" %>
  <%= f.input :address, label: "Διεύθυση" %>
  <%= f.input :city, label: "Πόλη" %>
  <%= f.input :phone, label: "Τηλέφωνο" %>
  <%= f.button :submit, "Δημιουργία νέου καταστήματος", class: "btn btn-primary" %>
<% end %>

app/views/shops/show.html.erb
<h1><%= @shop.name %></h1>
<h3><%= @shop.user.first_name %> <%= @shop.user.last_name %></h3>
<h3><%= @shop.address %></h3>
<h3><%= @shop.city %></h3>
<h3><%= @shop.phone %></h3> <br>
<%= link_to "Επεξεργασία", edit_shop_path(@shop), class: "btn btn-primary" %>