config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :shops, except: %i[destroy]
  resources :cloths
  resources :shelves, :colors, :types, except: :show

  get '/managments', to: 'managments#shop', as: 'managments'
  get '/managments/main', to: 'managments#main', as: 'managment_main'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cloth.rb
class Cloth < ApplicationRecord
  belongs_to :shelf
  belongs_to :color
  belongs_to :type
  belongs_to :user
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :cloths
end

app/models/shelf.rb
class Shelf < ApplicationRecord
  belongs_to :shop
  has_many :cloths
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :shelves
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :cloths
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:customer, :owner]
  belongs_to :shop, optional: true
  has_many :cloths
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    "#{last_name}, #{first_name}"
  end
end

app/controllers/cloths_controller.rb
class ClothsController < ApplicationController
  before_action :set_cloth, except: %i[index new create]

  def index
    if current_user.owner?
      @cloths = policy_scope(Cloth.where("shelf_id = ?", current_user.shop.shelf_ids))
      # raise
    else
      @cloths = policy_scope(Cloth.where("user_id = ?", current_user.id))
    end
  end

  def show
    authorize(@cloth)
  end

  def new
    @cloth = Cloth.new
    authorize(@cloth)
  end

  def create
    @cloth = Cloth.new(cloth_params)
    authorize(@cloth)
    @cloth.user = current_user
    @cloth.save!
    redirect_to cloth_path(@cloth)
  end

  def edit
  end

  def update
    @cloth.update(cloth_params)
  end

  def destroy
    @cloth.destroy
  end

  private

  def set_cloth
    @cloth = Cloth.find(params[:id])
  end

  def cloth_params
    params.require(:cloth).permit(:type_id, :color_id, :shelf_id, :category,
    :wash_type, :delivery, :completed, :pick_up_date, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  
  def home
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[show edit update]

  def index
    @shops = policy_scope(Shop.where(user_id: current_user.id))
  end

  def show
    authorize(@shop)
  end

  def new
    @shop = Shop.new
    authorize(@shop)
  end

  def create
    @shop = Shop.new(shop_params)
    authorize(@shop)
    @shop.user = current_user

    if @shop.save
      redirect_to shop_path(@shop)
      current_user.shop = @shop
      current_user.save
    else
      render 'shops/new'
    end
  end

  def edit
    authorize(@shop)
  end

  def update
    authorize(@shop)
    if @shop.update(shop_params)
      redirect_to shop_path(@shop)
    else
      redirect_to shop_path(@shop)
    end
  end

  private

  def set_shop
    @shop = Shop.find_by user_id: current_user.id
  end

  def shop_params
    params.require(:shop).permit(:name, :address, :phone, :city)
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController

  def new
    @type = Type.new
    authorize(@type)
  end

  def create
    @type = Type.new(type_params)
    authorize(@type)
    if @type.save!
      redirect_to managment_main_path
    else
      render "types/new"
    end
  end

  def update
    @type = Type.find(params[:id])
    authorize(@type)
    @type.update(type_params)
    redirect_to managment_main_path
  end

  private

  def type_params
    params.require(:type).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/cloths_helper.rb
module ClothsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/managments_helper.rb
module ManagmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shelves_helper.rb
module ShelvesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aparamillo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  </head>

  <body>
    <%= yield %>



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/_singed_in_user.html.erb
<div class="box col-12 col-sm-4 col-md-4 col-xl-4 text-center">
  <% if current_user.shop_id == nil && current_user.owner? %>
    <%= link_to "Δημιουργία καταστήματος", new_shop_path, class: "btn btn-lg btn-primary" %>
  <% elsif current_user.owner? %>
    <%= link_to "Προβολή ραφιών", shelves_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "Εισαγωγή ρούχου", new_cloth_path, class: "btn btn-lg btn-primary" %>
  <% else %>
    <%= link_to "Προβολή των ρούχων μου", cloths_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>
<div class="box col-12 col-sm-4 col-md-4 col-xl-4 text-center">
</div>

app/views/pages/home.html.erb
<div class="container-fluid  d-flex flex-column">
  <div class="header col-sm-8 offset-sm-2 col-md-8 col-lg-6 col-xl-4">
    ΚΑΘΑΡΙΣΤΗΡΙΟ <br>
      ΑΠΑΡΑΜΙΛΛΟ
    <div class="header-text">
      <br>
      Απαράμιλλη καθαριότητα και περιποίηση που επιτυγχάνεται με φυσική αφαίρεση
      λεκέδων και προστασία κατά της διάβρωσης των ρούχων.
    </div>
  </div>
  <div class="box-container">
    <div class="col-0 col-sm-2 col-md-2 col-xl-2"></div>
      <% if user_signed_in? %>
        <%= render "singed_in_user" %>
      <% end %>
    <div class="col-0 col-sm-2 col-md-2 col-xl-2"></div>
  </div>
</div>

<div class="d-flex justify-content-around pt-5">

  <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="https://st2.depositphotos.com/3045469/7822/v/450/depositphotos_78225880-stock-illustration-delivery-truck-sketch.jpg" alt="Card image cap">
    <div class="card-body">
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
  </div>

<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="https://st2.depositphotos.com/3045469/7822/v/450/depositphotos_78225880-stock-illustration-delivery-truck-sketch.jpg" alt="Card image cap">
    <div class="card-body">
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
  </div>

<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="https://st2.depositphotos.com/3045469/7822/v/450/depositphotos_78225880-stock-illustration-delivery-truck-sketch.jpg" alt="Card image cap">
    <div class="card-body">
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
  </div>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand nav-position" id="bg-color">
  <a class="navbar-brand" href="/">Απαράμιλλο</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto d-flex">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Ρούχα
        </a>
        <div class="dropdown-menu" id="dropdown-items-style" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/cloths">Τα ρούχα μου</a>
          <a class="dropdown-item" href="/cloths/new">Προσθήκη ρούχου</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown ml-auto">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false"> onoma
          <i class="fas fa-user"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-default"
          aria-labelledby="navbarDropdownMenuLink-333" id="dropdown-items-style">
          <a class="dropdown-item" href="/managments/main">Managment</a>
          <a class="dropdown-item" href="/shops">Διαχείρηση καταστήματος</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="/users/sign_out" data-method="delete">log out</a>
        </div>
      </li>
    </ul>
  </div>
</nav>